version: 0.0.1
os: linux
hooks:
  BeforeInstall:
    - location: /var/www/PaintingWithData_Riyadh/beforeinstall.sh
      timeout: 300
  AfterInstall:
    - location: /var/www/PaintingWithData_Riyadh/install.sh
      timeout: 300