export const SIDE_ADD_LAYER = "SIDE_ADD_LAYER";
export const SIDE_ADD_LAYERS = "SIDE_ADD_LAYERS";
export const SIDE_REMOVE_LAYER = "SIDE_REMOVE_LAYER";
export const SIDE_CHANGE_OPACITY = "CHANGE_OPACITY";
export const SIDE_UPDATE_LAYER = "SIDE_UPDATE_LAYER";

export const MAP_ADD_INSTANCE = "MAP_ADD_INSTANCE";
export const MAP_ADD_GEOMETRY = "MAP_ADD_GEOMETRY";

export const VLANG_ADD_LINK = "VLANG_ADD_LINK";
export const VLANG_REMOVE_LINK = "VLANG_REMOVE_LINK";
export const VLANG_ADD_NODE = "VLANG_ADD_NODE";
export const VLANG_REMOVE_NODE = "VLANG_REMOVE_NODE";
export const VLANG_UPDATE_NODE_POSITION = "VLANG_UPDATE_NODE_POSITION";

export const VLANG_ADD_LAYERS = "VLANG_ADD_LAYERS";

export const LAYER_NODE = "LAYER_NODE";
export const ADDITION_NODE = "ADD_NODE";
export const MULTIPLICATION_NODE = "MULTIPLICATION_NODE";
export const DIVISION_NODE = "DIVISION_NODE";
export const AND_NODE = "AND_NODE";
export const OR_NODE = "OR_NODE";
export const NOT_NODE = "NOT_NODE";
export const LOG_NODE = "LOG_NODE";


