export const SIDE_ADD_LAYER = "SIDE_ADD_LAYER";
export const SIDE_ADD_LAYERS = "SIDE_ADD_LAYERS";
export const SIDE_REMOVE_LAYER = "SIDE_REMOVE_LAYER";
export const SIDE_CHANGE_OPACITY = "CHANGE_OPACITY";
export const SIDE_UPDATE_LAYER = "SIDE_UPDATE_LAYER";

export const MAP_ADD_INSTANCE = "MAP_ADD_INSTANCE";
export const MAP_ADD_GEOMETRY = "MAP_ADD_GEOMETRY";


